blog/urls.py
app_name = "blog"

from django.urls import path
from .views.blogs_views import (
    BlogListAPIView,
    BlogUpdateDestroyAPIView,
    BlogCreateAPIView,
    BlogRetrieveAPIView,
)
from .views.serve_file_views import FileServeView, ThumbnailServeView
from .views.shortnotice_views import (
    ShortNoticeListAPIView,
    ShortNoticeCreateAPIView,
    ShortNoticeUpdateDestroyAPIView,
)

urlpatterns = [
    path("", BlogListAPIView.as_view(), name="blog-lists"),
    path("create/", BlogCreateAPIView.as_view(), name="blog-create"),
    path(
        "<slug:slug>/",
        BlogUpdateDestroyAPIView.as_view(),
        name="blog-update-destroy",
    ),
    path(
        "detail/<slug:slug>/",
        BlogRetrieveAPIView.as_view(),
        name="blog-update-destroy",
    ),
    path("notices/", ShortNoticeListAPIView.as_view(), name="shortnotice-list"),
    path(
        "notice/create/", ShortNoticeCreateAPIView.as_view(), name="shortnotice-create"
    ),
    path(
        "notice/<int:pk>/",
        ShortNoticeUpdateDestroyAPIView.as_view(),
        name="shortnotice-update-destroy",
    ),
    path("md/<slug:slug>/", FileServeView.as_view(), name="file-serve"),
    path("thumbnail/<str:img>/", ThumbnailServeView.as_view(), name="thumbnail-serve"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("blogs/", include("blog.urls", namespace="blogs")),
    path("", include("dashboard.urls", namespace="dashboard")),
]
if not settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns(
        [
            static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
            static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
        ]
    )

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
app_name = "dashboard"

from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from dashboard import views

urlpatterns = [
    path("", views.DashboardView.as_view(), name="home"),
    path('login/', LoginView.as_view(template_name="dashboard/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("user_create/", views.CreateUserView.as_view(), name="create-user"),
]

blog/models.py
from django.db import models
from django.utils.text import slugify
from .utils import file_md_validate, mail_validation, get_upload_folder, file_img_validate
import uuid
import os

class BlogCategory(models.TextChoices):
    NEWS_AND_ANNOUNCEMENT = "news_and_announcement", "News And Announcement"
    EVENT = "event", "Event"
    GENERAL = "general", "General"
    ACADEMICS = "academics", "Academics"
    PARENTS_RESOURCE = "parents_resource", "Parents Resource"
    CAREER = "career", "Career"
    ACHIEVEMENTS = "acheivements", "Achievements"
    POLICIES = "school_policies_guidelines", "School Policies And Guidelines"
    HEALTH = "health_wellness", "Health and Wellness"
    TECHNOLOGY = "technology", "Technology"
    ARTS = "arts", "Arts"
    SCIENCE = "science", "Science"

class NoticeTag(models.TextChoices):
    EVENT = "event", "Event"
    NEWS = "news", "News"


class Blog(models.Model):
    slug = models.CharField(max_length=260, null=True, blank=True)
    topic = models.CharField(max_length=255, blank=False, null=False)
    description = models.CharField(max_length=255*2, blank=False, null=False)
    thumbnail = models.ImageField(upload_to="thumbnails", validators=[file_img_validate], null=False, blank=False)
    author = models.CharField(max_length=255, blank=False, null=False)
    is_approved = models.BooleanField(default=False)
    is_rejected = models.BooleanField(default=False)
    mail = models.EmailField(null=False, blank=False, validators=[mail_validation])
    file = models.FileField(upload_to=get_upload_folder, validators=[file_md_validate], null=False, blank=False)
    category = models.CharField(max_length=255, choices=BlogCategory.choices, null=False, blank=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.author} | {self.topic[:20]}...'

    def get_file_name(self):
        return "blogs/" + f"{self.slug}-blog.md"

    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = f"{slugify(self.topic)}" + "-" + str(uuid.uuid4())[:6]
        return super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        os.remove(self.file.path)
        self.file.delete(False)
        return super().delete(*args, **kwargs)


class ShortNotice(models.Model):
    title = models.CharField(max_length=64*8, null=False, blank=True)
    content = models.TextField()
    issued_by = models.CharField(max_length=255, null=False, blank=False)
    designation = models.CharField(max_length=255, null=False, blank=False)
    tag = models.CharField(max_length=255, choices=NoticeTag.choices)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.title[:20]}.... | {self.issued_by}"

dashboard/models.py
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

    def __str__(self) -> str:
        return f"{self.username}"

dashboard/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .froms import UserCreateForm
from .mixins import IsStaffMixin
from django.contrib.auth.mixins import LoginRequiredMixin

class DashboardView(LoginRequiredMixin, IsStaffMixin, generic.TemplateView):
    template_name = "dashboard/index.html"
    def get(self, *args, **kwargs):
        return render(self.request, self.template_name, {})
    
class CreateUserView(LoginRequiredMixin, IsStaffMixin, generic.CreateView):
    form_class = UserCreateForm
    template_name = "dashboard/create_user.html"
    success_url = reverse_lazy("dashboard:home")

templates/dashboard/create_user.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
{%load tailwind_filters %}

<div class="flex h-screen bg-gray-50 dark:bg-gray-900" :class="{ 'overflow-hidden': isSideMenuOpen }">
    {% include 'dashboard/components/sidebar.html' %}
    <div class="flex flex-col flex-1 w-full">

        {% include 'dashboard/components/navbar.html' %}

        <main class="h-full overflow-y-auto my-8">
            <div class="container px-6 mx-auto grid">
                <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
                    Create System User
                </h2>
                <form action="" method="post">
                    {%csrf_token%}
                    {{form | crispy}}
                    <div class="mb-2"></div>
                    <button type="submit"
                        class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple w-full">
                        Create
                    </button>
                </form>
            </div>
        </main>
    </div>
</div>

{% endblock %}

templates/dashboard/index.html
{% extends 'base.html' %}
{% block title %} Dashboard | Seller {% endblock %}
{% block content %}
    <div
      class="flex h-screen bg-gray-50 dark:bg-gray-900"
      :class="{ 'overflow-hidden': isSideMenuOpen }"
    >
    {% include 'dashboard/components/sidebar.html' %}
    
    <div class="flex flex-col flex-1 w-full">

        {% include 'dashboard/components/navbar.html' %}

        <main class="h-full overflow-y-auto">
          <div class="container px-6 mx-auto grid">
            <h2
              class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200"
            >
              Dashboard
            </h2>
            <!-- CTA -->

            {% include 'dashboard/components/cards.html' %}

            <!-- Charts -->
            <h2
              class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200"
            >
              System Users
            </h2>
            {% include 'dashboard/components/table.html' %}

            {% if perms.blog.view_blog %}
            <h2
              class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200"
            >
              Blogs
            </h2>
            <!-- New Table -->
            {% include 'dashboard/components/table_with_action.html' %}
            {% endif %}


          </div>
        </main>
      </div>
    </div>

{% endblock %}

templates/dashboard/inventory.html
{% extends 'base.html' %}
{% block title %} Blogs | Dashboard {% endblock %}

{% block content %}
<div class="flex h-screen bg-gray-50 dark:bg-gray-900" :class="{ 'overflow-hidden': isSideMenuOpen }">

  {% include 'dashboard/components/sidebar.html' %}

  <div class="flex flex-col flex-1 w-full">

    {% include 'dashboard/components/navbar.html' %}

    <main class="h-full overflow-y-auto">
      <div class="container px-6 mx-auto grid">
        <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
          Inventory
        </h2>

        <div class="w-full overflow-hidden rounded-lg shadow-xs">
          <div class="w-full overflow-x-auto">
            <table class="w-full whitespace-no-wrap">
              <thead>
                <tr
                  class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                  <th class="px-4 py-3">Product</th>
                  <th class="px-4 py-3">Amount</th>
                  <th class="px-4 py-3">Quantity</th>
                  <th class="px-4 py-3">Stocked at</th>
                  <th class="px-4 py-3">Discount</th>
                  <th class="px-4 py-3">Actions</th>
                </tr>
              </thead>
              <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                {% for product in products %}
                <tr class="text-gray-700 dark:text-gray-400">
                  <td class="px-4 py-3">
                    <div class="flex items-center text-sm">
                      <!-- Avatar with inset shadow -->
                      <!-- <div class="relative hidden mr-3 rounded-full md:block"> -->
                      <img class="object-cover" src="{{product.thumbnail}}" alt="" loading="lazy" height="90px"
                        width="90px" />
                      <!-- <div class="absolute inset-0 rounded-full shadow-inner" aria-hidden="true"></div> -->
                      <!-- </div> -->
                      <div class="ml-2">
                        <p class="font-semibold">{{product.title}}</p>
                        <p class="text-xs text-gray-600 dark:text-gray-400">
                          {{product.slug}}
                        </p>
                      </div>
                    </div>
                  </td>
                  <td class="px-4 py-3 text-sm">
                    $ {{product.net_price}}
                  </td>
                  <td class="px-4 py-3 text-sm">
                    {{product.quantity}}
                    {% if product.quantity == 0 %}
                    <span
                      class="ml-4 p-1 font-semibold leading-tight text-red-700 bg-red-100 text-sm  rounded-md dark:text-white dark:bg-orange-600">
                      No stock
                    </span>
                    {% elif product.quantity > 0 and product.quantity < 6 %} <span
                      class="ml-4 p-1 font-semibold leading-tight text-orange-700 bg-orange-100 text-sm  rounded-md dark:text-white dark:bg-orange-600">
                      Low
                      </span>
                      {% endif %}
                  </td>
                  <td class="px-4 py-3 text-sm">
                    {{product.created_at}}
                  </td>
                  <td class="px-4 py-3 text-sm">
                    {{product.discount_percent}} %
                    {% if product.discount_percent > 0 and product.discount_percent < 2.5 %} 
                    <span
                      class="ml-4 p-1 font-semibold leading-tight text-green-700 bg-green-100 text-sm  rounded-md dark:text-white dark:bg-orange-600">
                      Low
                      </span>
                      {% elif product.discount_percent > 50 %}
                      <span
                        class="ml-4 p-1 font-semibold leading-tight text-red-700 bg-red-100 text-sm  rounded-md dark:text-white dark:bg-orange-600">
                        High
                      </span>
                    {% endif %}
                  </td>
                  <td class="px-4 py-3">
                    <div class="flex items-center space-x-4 text-sm">
                      <button
                        class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray"
                        aria-label="Edit">
                        <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                          <path
                            d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z">
                          </path>
                        </svg>
                      </button>
                      <button
                        class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray"
                        aria-label="Delete">
                        <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                          <path fill-rule="evenodd"
                            d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                            clip-rule="evenodd"></path>
                        </svg>
                      </button>
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <div
            class="grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 uppercase border-t dark:border-gray-700 bg-gray-50 sm:grid-cols-9 dark:text-gray-400 dark:bg-gray-800">
            <span class="flex items-center col-span-3">
              Showing 21-30 of 100
            </span>
            <span class="col-span-2"></span>
            <!-- Pagination -->
            <span class="flex col-span-4 mt-2 sm:mt-auto sm:justify-end">
              <nav aria-label="Table navigation">
                {% if is_paginated %}
                <ul class="inline-flex items-center">
                  {% if page_obj.has_previous %}
                  <li>
                    <a href="?page={{ page_obj.previous_page_number }}">
                      <button class="px-3 py-1 rounded-md rounded-l-lg focus:outline-none focus:shadow-outline-purple"
                      aria-label="Previous">
                      <svg class="w-4 h-4 fill-current" aria-hidden="true" viewBox="0 0 20 20">
                        <path
                        d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                        clip-rule="evenodd" fill-rule="evenodd"></path>
                      </svg>
                    </button>
                  </a>
                  </li>
                  {% endif %}
                  <li>
                    <button class="px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple">
                      1
                    </button>
                  </li>
                  <li>
                    <button class="px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple">
                      2
                    </button>
                  </li>
                  <li>
                    <button
                      class="px-3 py-1 text-white transition-colors duration-150 bg-purple-600 border border-r-0 border-purple-600 rounded-md focus:outline-none focus:shadow-outline-purple">
                      3
                    </button>
                  </li>
                  <li>
                    <button class="px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple">
                      4
                    </button>
                  </li>
                  <li>
                    <span class="px-3 py-1">...</span>
                  </li>
                  <li>
                    <button class="px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple">
                      8
                    </button>
                  </li>
                  <li>
                    <button class="px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple">
                      9
                    </button>
                  </li>
                  <li>
                    <button class="px-3 py-1 rounded-md rounded-r-lg focus:outline-none focus:shadow-outline-purple"
                      aria-label="Next">
                      <svg class="w-4 h-4 fill-current" aria-hidden="true" viewBox="0 0 20 20">
                        <path
                          d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                          clip-rule="evenodd" fill-rule="evenodd"></path>
                      </svg>
                    </button>
                  </li>
                </ul>
                {% endif %}
              </nav>
            </span>
          </div>
        </div>


      </div>
    </main>
  </div>
</div>

{% endblock %}

templates/dashboard/login.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
{%load tailwind_filters %}
<div class="h-screen flex justify-center items-center">
    <div style="max-width: 400px;">
        <div class="w-full flex justify-center">
            <lord-icon src="https://cdn.lordicon.com/dxjqoygy.json" trigger="hover"
                colors="primary:#121331,secondary:#e83a30" style="width:80px;height:80px">
            </lord-icon>
        </div>
        <div class="w-full flex justify-center" style="margin-bottom: 20px;">
            <h1 class="text-xl font-semibold text-gray-700 my-2">Welcome Back!</h1>
        </div>
        <form action="" method="post">
            {%csrf_token%}
            {{form | crispy}}
            <div class="w-full flex justify-center mb-4" style="margin-top: 10px;"><a href="" class="text-sm" style="color: rgb(10, 100, 236);">Don't have an account?</a></div>
            <button
                class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple w-full">
                Login
            </button>
        </form>
    </div>
</div>

{% endblock %}

templates/dashboard/scripts.html
{% load static %}

<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
<link rel="stylesheet" href="{% static 'dashboard/css/tailwind.output.css' %}" />
<!-- <script src="https://cdn.tailwindcss.com"></script> -->

<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
<script src="{% static 'dashboard/js/init-alpine.js' %}"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" defer></script>
<script src="{% static 'dashboard/js/charts-lines.js' %}" defer></script>
<script src="{% static 'dashboard/js/charts-pie.js' %}" defer></script>
<script src="https://cdn.lordicon.com/fudrjiwc.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>